Update update

diff --git a/scripts/commands.d/update b/scripts/commands.d/update
--- a/scripts/commands.d/update
+++ b/scripts/commands.d/update
@@ -58,8 +58,8 @@ else
     plugin="${i%%:*}"
     if [ -d "$PLUGINDIR/$plugin" ]; then
       release="${i##*:}"
-      if [[ "$release" == "$i" ]]; then
-        for j in "$i"/*; do
+      if [[ "$release" == "$i" ]] || [[ "$release" == "" ]]; then
+        for j in "$PLUGINDIR/$plugin"/*; do
           if [ -d "$j" ]; then
             release="${j##*/}"
             echo "Updating $plugin:$release..."
@@ -68,7 +68,7 @@ else
         done
       elif [ -d "$PLUGINDIR/$plugin/$release" ]; then
         echo "Updating $plugin:$release..."
-        (cd "$j" && "$MAKE") >"$output" || echo "Failed to update $plugin:$release" >&2
+        (cd "$PLUGINDIR/$plugin/$release" && "$MAKE") >"$output" || echo "Failed to update $plugin:$release" >&2
       else
         echo "$0: no release '$release' in package '$plugin'" >&2
       fi
